apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo
data:
  config.yaml: |
    log:
      level: info
    container:
      privileged: true
      network: host
