---
- name: Include OS-specific k3s setup
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Create .kube directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: "0755"

- name: Wait for k3s API server to be reachable
  ansible.builtin.command: kubectl get nodes
  changed_when: false
  retries: 12
  delay: 10
  register: k3s_api
  until: k3s_api.rc == 0
