---
- name: restart dnsmasq macos
  ansible.builtin.shell: |
    launchctl unload /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist 2>/dev/null || true
    launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  become: true
  changed_when: false

- name: restart dnsmasq linux
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
  become: true

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true
