---
- name: Tap fluxcd homebrew repository
  community.general.homebrew_tap:
    name: fluxcd/tap
    state: present

- name: Ensure Homebrew packages are installed
  community.general.homebrew:
    name:
      - jq
      - kubectl
      - helm
      - lima
      - fluxcd/tap/flux
      - mkcert
      - cosign
      - kubeseal
    state: present

- name: Install mkcert CA into system trust store
  ansible.builtin.command: mkcert -install
  changed_when: false
